# Generated by Django 3.2.3 on 2021-05-17 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dateOfBirth', models.DateField()),
                ('balance', models.IntegerField()),
                ('accountNumbers', models.CharField(default=' ', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionId', models.CharField(max_length=10)),
                ('FromAccNo', models.CharField(max_length=5)),
                ('ToAccNo', models.CharField(max_length=5)),
                ('Amount', models.IntegerField()),
                ('dateTime', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
